name: Django CI + Docker Build

on:
  push:
    branches: [ "ci-setup" ]
  pull_request:
    branches: [ "ci-setup" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirimientos.txt

      - name: Run tests
        env:
          DB_ENGINE: django.db.backends.sqlite3
          DB_DATABASE: db.sqlite3
          DB_USERNAME: ""
          DB_PASSWORD: ""
          DB_SOCKET: ""
          DB_PORT: ""
        run: |
          python manage.py test

  docker-build:
    needs: build-and-test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t proy_sales_poo:latest .

      - name: Save Docker image as artifact
        run: |
          docker save proy_sales_poo:latest -o docker-image.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: docker-image.tar